title: Andy Brett
url: "https://andybrett.com"
permalink: /:categories/:title.html
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
kramdown:
  input: GFM
  hard_wrap: false
exclude: ["deploy.sh"]
baseurl: "/"
sitesource: https://github.com/andrewpbrett/andybrett.com
